### PR TITLE
Fixes firebase issue (MOBILE-966)

### PR DESCRIPTION
**Pull request by ldurazo**
Same changes as: 

https://github.com/arnesson/cordova-plugin-firebase/pull/1058/files

Might be the update we need, please test beforehand. Enabled deployment of the apk in my environment but the app had trouble running, i don't think is related to this changes however.

### CODE REVIEW

**Comment by ldurazo** [comment]
changing `config.xml` and `package.json` firebase references to
`git+ssh://git@github.com/zenput/cordova-plugin-firebase.git#fix-firebase`

this change can be tested locally.

**Comment by davidofwatkins** [comment]
Reposting here what I DM'd Luis for the record:

I gave this a try, and it seems to have fixed the build—with some other problems:

- I got the `pw-notification` error which broke the build, but I was able to fix this with `runphonegap.sh --reinstall-platforms` afterwards. Something strange is going on there...
- The app installs, but it crashes immediately with the following stack trace:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceIdService;
E      at java.lang.Class.classForName(Native Method)
E      at java.lang.Class.forName(Class.java:453)
E      at java.lang.Class.forName(Class.java:378)
E      at io.intercom.android.sdk.IntercomPushManager.getFcmInstanceIdClass(IntercomPushManager.java:105)
E      at io.intercom.android.sdk.IntercomPushManager.fcmModuleInstalled(IntercomPushManager.java:61)
E      at io.intercom.android.sdk.IntercomPushManager.getInstalledModuleType(IntercomPushManager.java:41)
E      at io.intercom.android.sdk.IntercomBridge.setUpIntercom(IntercomBridge.java:65)
E      at io.intercom.android.sdk.IntercomBridge.access$000(IntercomBridge.java:27)
E      at io.intercom.android.sdk.IntercomBridge$1.run(IntercomBridge.java:34)
E      at android.app.Activity.runOnUiThread(Activity.java:6283)
E      at io.intercom.android.sdk.IntercomBridge.pluginInitialize(IntercomBridge.java:32)
E      at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:58)
E      at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
E      at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
E      at org.apache.cordova.PluginManager.init(PluginManager.java:86)
E      at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:117)
E      at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
E      at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
E      at com.zenput.mobile.MainActivity.onCreate(MainActivity.java:39)
E      at android.app.Activity.performCreate(Activity.java:7144)
E      at android.app.Activity.performCreate(Activity.java:7135)
E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
E      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
E      at android.os.Handler.dispatchMessage(Handler.java:106)
E      at android.os.Looper.loop(Looper.java:193)
E      at android.app.ActivityThread.main(ActivityThread.java:6718)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ldurazo** [comment]
Can this be merged? Fix on zenput-core requires this merge beforehand. The issue described by David has already been fixed on a zenput-core branch.

**Comment by gmotzespina** [comment]
> Can this be merged? Fix on zenput-core requires this merge beforehand. The issue described by David has already been fixed on a zenput-core branch.

@ldurazo Normally in Zenput's core app, the protocol is that you assign a reviewer if the reviewer approves it. Then you mark it as RTM (Ready To Merge) and @davidemerritt merges it. Not sure If on this repo the protocol is the same. @davidofwatkins

**Review by davidofwatkins — APPROVED** [review]
Sweet, lgtm! Thanks for taking care of this @ldurazo 🙌 These sorts of issues are always a pain.

As for @gmotzespina's note about `RTM`s, that's mostly just for the core codebase since everything's a little more complicated with deployments, etc. there. (Eventually they'll move to more of a merge-when-ready system.)

**Comment by ldurazo** [comment]
thanks @gmotzespina ! i'll be sure to follow those steps on core and I needed a refresh on that.

Also thanks @davidofwatkins for the approval :) merging now.

**Pull request merged**
